# Generated by Django 5.2 on 2025-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0002_categoria_alter_pedido_monto_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=10, help_text='Un número más bajo aparece primero'),
        ),
    ]
