# Generated by Django 5.2.3 on 2025-06-28 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0006_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del turno.')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de finalización del turno.')),
                ('camarero', models.ForeignKey(help_text='Camarero asignado a este turno.', limit_choices_to={'rol': 'CAMARERO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
