# Generated by Django 5.2 on 2025-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0007_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_secreto_camarero',
            field=models.CharField(blank=True, help_text='Código secreto para camareros (4 dígitos)', max_length=10, null=True, unique=True),
        ),
    ]
