# Generated by Django 5.2.3 on 2025-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0008_usuario_codigo_secreto_camarero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Oferta de Verano', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 10.00) o monto fijo (ej: 1000)', max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('productos_afectados', models.ManyToManyField(blank=True, related_name='promociones', to='restaurante_app.producto')),
            ],
        ),
    ]
