# Generated by Django 5.2.3 on 2025-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0010_pedidodetalle_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.IntegerField(default=0, help_text='Monto de la propina añadida al pedido'),
        ),
    ]
